/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ArchivesIndexRouteImport } from './routes/archives/index'
import { Route as DailyAddRouteImport } from './routes/daily/add'
import { Route as ArchivesGameIdRouteImport } from './routes/archives/$gameId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchivesIndexRoute = ArchivesIndexRouteImport.update({
  id: '/archives/',
  path: '/archives/',
  getParentRoute: () => rootRouteImport,
} as any)
const DailyAddRoute = DailyAddRouteImport.update({
  id: '/daily/add',
  path: '/daily/add',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchivesGameIdRoute = ArchivesGameIdRouteImport.update({
  id: '/archives/$gameId',
  path: '/archives/$gameId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/archives/$gameId': typeof ArchivesGameIdRoute
  '/daily/add': typeof DailyAddRoute
  '/archives': typeof ArchivesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/archives/$gameId': typeof ArchivesGameIdRoute
  '/daily/add': typeof DailyAddRoute
  '/archives': typeof ArchivesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/archives/$gameId': typeof ArchivesGameIdRoute
  '/daily/add': typeof DailyAddRoute
  '/archives/': typeof ArchivesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/archives/$gameId' | '/daily/add' | '/archives'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/archives/$gameId' | '/daily/add' | '/archives'
  id: '__root__' | '/' | '/archives/$gameId' | '/daily/add' | '/archives/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArchivesGameIdRoute: typeof ArchivesGameIdRoute
  DailyAddRoute: typeof DailyAddRoute
  ArchivesIndexRoute: typeof ArchivesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/archives/': {
      id: '/archives/'
      path: '/archives'
      fullPath: '/archives'
      preLoaderRoute: typeof ArchivesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/daily/add': {
      id: '/daily/add'
      path: '/daily/add'
      fullPath: '/daily/add'
      preLoaderRoute: typeof DailyAddRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/archives/$gameId': {
      id: '/archives/$gameId'
      path: '/archives/$gameId'
      fullPath: '/archives/$gameId'
      preLoaderRoute: typeof ArchivesGameIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArchivesGameIdRoute: ArchivesGameIdRoute,
  DailyAddRoute: DailyAddRoute,
  ArchivesIndexRoute: ArchivesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
